# Crie um programa em Python que peça dois números ao usuário.
# Em seguida, você vai mostrar a soma, subtração, multiplicação, divisão, exponenciação e 
# resto da divisão do primeiro número pelo segundo.

num1 = int(input('Digite um número: '))
num2 = int(input('Digite um número: '))
print(f'soma: {num1+num2}')
print(f'subtração: {num1-num2}')
print(f'multiplicação: {num1*num2}')
print(f'divisão: {num1/num2}')
print(f'exponenciação: {num1**num2}')
print(f'resto: {num1%num2}')